version: "3"

services :

  DB:
    image: 'postgres'
    container_name: DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=c2VjcmV0
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - DB:/var/lib/postgres/data
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql

  API:
    image: 'api-docker.jar'
    container_name: API
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DB:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=c2VjcmV0
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - DB

volumes:
  DB:
    driver: local